### ISSUE TITLE
RuntimeError: invalid argument 5: k not in range for dimension at /pytorch/aten/src/THC/generic/THCTensorTopK.cu:24

### ISSUE THREAD

**Issue by Felix-fz** [quotation2520/PG-RCNN#1]
Hi, when I run this project, I met this question. I had search this, it look like maybe the parameter of topk is set wrong. But I do not  know how to solve it. Could you help me, thanks！

Traceback (most recent call last):
  File "/opt/conda/envs/pcdet/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/envs/pcdet/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/workspace/PG-RCNN/pcdet/datasets/multifindbestfit.py", line 488, in <module>
    sorted_iou, best_iou_indices = torch.topk(iou3d, min(800, len(iou3d)), dim=-1, sorted=True, largest=True)
RuntimeError: invalid argument 5: k not in range for dimension at /pytorch/aten/src/THC/generic/THCTensorTopK.cu:24

**Comment by quotation2520** [comment]
Hi, thank you for your interest in our work!

We adopted the implementation of pcdet/datasets/multifindbestfit.py from [BtcDet](https://github.com/Xharlie/BtcDet/blob/main/btcdet/datasets/multifindbestfit.py).
You may notice that we only modified the paths to fetch and save the data.

We were not able to reproduce the error you have encountered in our environment. (python 3.8, pytorch 1.10)
What is your Python/Pytorch version?

**Comment by Felix-fz** [comment]
Python/Pytorch version is 3.7.11/(1.8.1+cu111) in my environment. Would you release the docker image of your environment？

**Comment by Felix-fz** [comment]
I have set my Python/Pytorch version is 3.8/1.10, but there is still the wrong. Maybe you had set something on the dataset?

14356/14357: bm_vox_num 0, bm_pnt_num 0 
ROOT_DIR /workspace/PG-RCNN
iou3d torch.Size([734, 734])
coords_num torch.Size([734]) tensor(0, device='cuda:0') tensor(53, device='cuda:0')
coord_inds torch.Size([706])

Traceback (most recent call last):
  File "/opt/conda/envs/pgr/lib/python3.8/runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/envs/pgr/lib/python3.8/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/workspace/PG-RCNN/pcdet/datasets/multifindbestfit.py", line 488, in <module>
    sorted_iou, best_iou_indices = torch.topk(iou3d, min(800, len(iou3d)), dim=-1, sorted=True, largest=True)
RuntimeError: selected index k out of range

**Comment by 2in0** [comment]
We have identified the issue you mentioned and resolved it by code update [8b6543f](https://github.com/quotation2520/PG-RCNN/commit/8b6543f59d424b5de5f84aa60c65b2032eca326a), ensuring it no longer occurs.
The modified code produces the same results. 
Additionally, The authors of [BtcDet](https://github.com/Xharlie/BtcDet) share the preprocessed data ([link](https://drive.google.com/drive/folders/1mK4akt3Qro9nbw_NRfP__p2nb3a_rzxv)), so please refer to it if needed.

Thanks for letting us know about the problem in our code.
