### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by mirpouya** [quotation2520/PG-RCNN#12]
Hi, 
There are many dataset and links in KITTI-3D object, which one or which set of them we need for testing this model?

I mainly want to work with Lidar data not images.

**Comment by quotation2520** [comment]
You should check [GETTING_STARTED.md](https://github.com/open-mmlab/OpenPCDet/blob/master/docs/GETTING_STARTED.md) of OpenPCDet to fully utilize our work.
Please refer to the e-mail I sent you.
Thanks.
