### ISSUE TITLE
About Latency 

### ISSUE THREAD

**Issue by MAI-KOKO** [quotation2520/PG-RCNN#13]
Dear Author,

PG-RCNN is an excellent work!

I would like to ask you how you test Latency in your code?

Thank you very much!

**Comment by quotation2520** [comment]
Hi, thanks for your attention :)

The latency is described in Table 1 of our paper. We reported the average inference time on a single NVIDIA RTX 3090 GPU.

![image](https://github.com/quotation2520/PG-RCNN/assets/47216704/9b3625e3-34e1-4a8f-909d-f4d05d2fe8c8)

Thanks!

**Comment by MAI-KOKO** [comment]
Thank you for your timely reply!

I tried in demo.py:
              torch.cuda.synchronize()
              start_time = time.time()
              pred_dicts, _ = model.forward(data_dict)
              torch.cuda.synchronize()
              latency = time.time() - start_time
Testing the inference time, but the value seems to be different from the paper, is there something wrong with my operation?

Thank you very much!
