### ISSUE TITLE
INSTALLATION

### ISSUE THREAD

**Issue by mirpouya** [quotation2520/PG-RCNN#15]
I found your documents very insufficient and confusing to install.
What are the exact steps?
Which "setup.py" must be run?
the one in OpenPCDet repo, or the one in this repo?
Should I replace the files in your repo with the same ones in OpenPCDet?
please explain it in more detail

**Comment by mirpouya** [comment]
like I can install OpenPCDet with the following tutorial, and it installs pcdet version 0.6.0.
 https://medium.com/@alifyafebriana/setting-up-3d-open-source-openpcdet-with-anaconda-a-step-by-step-guide-66126107215

but according to your INSTALL.md, should I first install OpenPCDet and then run the setup.py in your repo? or should I even install OpenPCDet? buy running setup.py in your repo it will be installed, please explain it in more detail and guide me through it step by step.

thank you very much.

**Comment by quotation2520** [comment]
Hi,

Make a conda environment, install OpenPCDet following the tutorial, then run setup.py in this repo.

Thanks.
