### ISSUE TITLE
Why did you set ' has_label' of  'test'  to true?

### ISSUE THREAD

**Issue by Felix-fz** [quotation2520/PG-RCNN#2]
This is very strange. There is not 'label_2' in the 'test'. Why did you set ' has_label' of  'test'  to true?

    dataset.set_split('test')
    kitti_infos_test = dataset.get_infos(num_workers=workers, has_label=True, count_inside_pts=False)

**Comment by quotation2520** [comment]
We do not have the GT labels for the KITTI test split, and the evaluation can only be done at the official test server with a limited number of submissions (tokens).
We did not want to waste our tokens, so we tried to validate our model with pseudo-labels generated by a baseline detector (Voxel R-CNN).
Using our pseudo-labels (saved in label_2 of the 'testing' folder), we were able to visualize and compare the predictions of our model and the baseline model - like we do on the validation split.

We should have removed that part during our code wrap-up. I'm so sorry for your confusion.
You can simply set the 'has_label' option to False. Thank you for the notice!
