### ISSUE TITLE
The result of Voxel-RCNN in Table 1 of the paper.

### ISSUE THREAD

**Issue by weilli** [quotation2520/PG-RCNN#3]
Thanks for your work. The results I found in the Voxel-RCNN original paper are 92.38, 85.29, 82.86. And this paper are 91.72, 83.19, 78.60. Are there any other settings?

**Comment by quotation2520** [comment]
To measure the size and latency of the models, we re-evaluated the performance using the pre-trained weights provided by the official implementation (which is often lower than the performance written in the papers).
Nevertheless, we admit we mistakenly listed the wrong values for Voxel R-CNN.
When we re-evaluated Voxel R-CNN with the weights provided in OpenPCDet, the performances were 92.23, 85.03, 82.51, which is still lower than PG-RCNN.
We apologize for the error.
