### ISSUE TITLE
Model Size Incorresponding

### ISSUE THREAD

**Issue by hlesmqh** [quotation2520/PG-RCNN#4]
As mentioned, the proposed model size is about 8.8M. However, the download link gives a 26.2M file instead. (Second in OpenPCDet is 20.3M) Why?

**Comment by quotation2520** [comment]
We are sorry for the confusion.

We noticed that we have uploaded a .pth file that contains not only the model weights but other data also.
That is, a dictionary file that contains ```epoch, it, model_state, optimzier_state, (pcdet) version``` .
I believe the additional memory size is originated from the optimizer_state, which contains the gradients of our parameters.

8.8MB file is the pure memory size of our model weights (model_state), and we have fixed the download link to give you the weights only. You will be able to reproduce our results with the given file.
(The original 26.2M file can be found [here](https://drive.google.com/file/d/1tOQM4SKJsirc_WUxxAZrdl2RNuPZkVv8/view?usp=sharing).)

As mentioned in paper, PG-RCNN has a number of parameters 2.28M (2,276,148 in exact), which is significantly smaller than SECOND (5.33M). 

Again, we are sorry for your confusion and we thank you for your interest!
