### ISSUE TITLE
MjoduleNotFoundError

### ISSUE THREAD

**Issue by JSWLDG** [quotation2520/PG-RCNN#5]
ModuleNotFoundError: No module named 'pcdet.models.backbones_3d.vfe.image_vfe_modules.f2v.voxel_field_fusion'

from .frustum_to_voxel import FrustumToVoxel
from .frustum_to_voxel_with_point import FrustumToVoxelWithPoint
from .voxel_field_fusion import VoxelFieldFusion

__all__ = {
    'FrustumToVoxel': FrustumToVoxel,
    'FrustumToVoxelWithPoint': FrustumToVoxelWithPoint,
    'VoxelFieldFusion': VoxelFieldFusion,
}

I cannot find the voxel_filed_fusion

It will be thankful you answer this issue

**Comment by 2in0** [comment]
Thank you for bringing this error to our attention. We have identified and fixed the issue as follows. If you find any further errors or issues, please let us know at any time.



'pcdet.models.backbones_3d.vfe.image_vfe_modules.f2v.voxel_field_fusion'

from .frustum_to_voxel import FrustumToVoxel
from .frustum_to_voxel_with_point import FrustumToVoxelWithPoint

__all__ = {
    'FrustumToVoxel': FrustumToVoxel,
    'FrustumToVoxelWithPoint': FrustumToVoxelWithPoint,
}
