### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by XLLXO** [quotation2520/PG-RCNN#8]
Hello author
I'm having some problems with your code.
I would like to ask you how to solve these problems.
The questions are as follows:
An error message is displayed indicating that the file cannot be found：/PG-RCNN /data/kitti/train_mirror_target/bm_50maxdist_2num_Car/3817_0.pkl'
May I ask how this problem should be solved?
Hope to get your reply,
thank you.
![ques1](https://github.com/quotation2520/PG-RCNN/assets/101243361/06dd1970-36a8-41d8-9f00-f07121129fdb)
![ques2](https://github.com/quotation2520/PG-RCNN/assets/101243361/2a19ed7c-e6cf-4aaa-b253-f0de6e9d6237)

**Comment by quotation2520** [comment]
Hi, you have to first preprocess the dataset using the command below. (It's mentioned on README.)

![image](https://github.com/quotation2520/PG-RCNN/assets/47216704/de7118e6-bea6-4741-81a5-573740721340)

This will find and assign the best-matching objects of each object instance for approximating the complete point cloud.

Thanks!
