### ISSUE TITLE
some error with the demo.py

### ISSUE THREAD

**Issue by ZhaZhahe** [quotation2520/PG-RCNN#9]
Thanks for your great work.
When I run the demo.py with command of 
"python demo.py --cfg_file  ./cfgs/kitti_models/pgrcnn.yaml --ckpt ./ckpt/pg_rcnn_weight.pth --data_path ./demo_data/000010.bin"
which is same as the Openpcdet's, and I encountered the following issue:
"
Traceback (most recent call last):
  File "demo.py", line 112, in <module>
    main()
  File "demo.py", line 89, in main
    model = build_network(model_cfg=cfg.MODEL, num_class=len(cfg.CLASS_NAMES), dataset=demo_dataset)
  File "/home/zhanghan/workspace/OpenPCDet/pcdet/models/__init__.py", line 17, in build_network
    model = build_detector(
  File "/home/zhanghan/workspace/OpenPCDet/pcdet/models/detectors/__init__.py", line 42, in build_detector
    model = __all__[model_cfg.NAME](
KeyError: 'PGRCNN'
"
It seem a simple issue, but I have no idea about it，could you tell me how to visualize？

**Comment by ZhaZhahe** [comment]
I might know the reason, the path has error...

**Comment by ZhaZhahe** [comment]
I have visualized it, it looks good.

**Comment by quotation2520** [comment]
Good to hear that. I'll close the issue, thanks for your interest!!
